# Generated by Django 3.1.3 on 2021-08-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='project', max_length=100),
            preserve_default=False,
        ),
    ]
